export const join = (req, res) => res.render("join")
export const login = (req, res) => res.render("login")
export const logout = (req, res) => res.render("logout")
export const showcase = (req, res) => res.render("showcase")
export const users = (req, res) => res.render("users")
export const userDetail = (req, res) => res.render("User Detail")
export const editProfile = (req, res) => res.render("Edit Profile")
export const changePassword = (req, res) => (req, res) => res.render("Change Password")